name = "ModelBaseEcon"
uuid = "1d16192e-b65e-11ea-11ed-0789cee22d2f"
authors = ["Boyan Bejanov <bbejanov@bankofcanada.ca>", "Nicholas Labelle St-Pierre <labs@bankofcanada.ca>", "Jason Jensen <jjensen@bankofcanada.ca>"]
version = "0.6.5"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ComponentArrays = "0.15"
Crayons = "4"
DiffResults = "1"
ForwardDiff = "1"
MacroTools = "0.5"
OrderedCollections = "1"
Printf = "1.8"
SparseArrays = "1.8"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
